// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Diagnostic logs for production environment
if (typeof window !== 'undefined') {
  console.log('--- SUPABASE INITIALIZATION DIAGNOSTIC ---');
  console.log('URL defined:', !!SUPABASE_URL);
  console.log('Key defined:', !!SUPABASE_PUBLISHABLE_KEY);
  console.log('Current Host:', window.location.host);
  if (SUPABASE_URL && !SUPABASE_URL.includes(window.location.host.split('.')[0]) && !SUPABASE_URL.includes('localhost')) {
    console.warn('Potential domain mismatch detected between app and Supabase project.');
  }
}

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("ERRO: Variáveis de ambiente do Supabase não encontradas. Verifique as configurações no Lovable.");
}

export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});