// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase: Variáveis de ambiente não encontradas no `import.meta.env`.");
} else {
  console.log("Supabase: Inicializando cliente...");
  console.log("Supabase: URL ->", SUPABASE_URL);
  // Log partially redacted key for safety but enough to verify it exists
  console.log("Supabase: Key detectada (comprimida) ->", SUPABASE_PUBLISHABLE_KEY.substring(0, 10) + "...");
}

export const supabase = createClient<Database>(SUPABASE_URL || "", SUPABASE_PUBLISHABLE_KEY || "", {
  auth: {
    storage: localStorage,
    storageKey: "ffh-original-recovery-v1", // Chave única para forçar reset de cache em todos os dispositivos
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
